#!/bin/sh

OUTFILE=build_info.h

if [ "x$1" = "x" ] ; then
    DIR=$PWD
else
    DIR=$1
fi

rm -f build_info.h
echo '/* autogenerated by make-build-info.sh */' > $OUTFILE
echo 'const char REVISION[] = "'$(cd $DIR && git rev-parse HEAD 2>/dev/null || echo "raw")'";' >> $OUTFILE
echo 'const char BUILD_DATE[] = "'$(date +%Y%m%d-%H%M%S)'";' >> $OUTFILE
