#!/bin/sh /etc/rc.common

#  Copyright (c) 2016 Kiban Labs Inc. All rights reserved.

START=90
STOP=15

USE_PROCD=1

# Check for diag mode.
local diag_env

check_diag() {
	diag_ch=`/usr/sbin/fw_printenv diag 2> /dev/null`
	diag_env=`echo $diag_ch | sed 's/diag=1/1/'`
}

check_diag

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/attrd
	procd_set_param respawn
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	procd_close_instance
}

stop() {
	procd_kill attrd
}

boot() {
    # commands to run at boot but not at restart

    # continue with the start() section
    start
}

restart() {
    stop "$@"
    start "$@"
}

shutdown() {
    stop
}
